services:
  valkey:
    image: valkey/valkey:latest
    restart: always
    volumes:
      - valkey-data:/data
  app:
    build: .
    command: pnpm --filter=next-app start
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - valkey
volumes:
  valkey-data: