services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    command: pnpm --filter=next-app start
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  pgdata: